var f;f||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},f),ba=(a,b)=>{throw b;},h="";"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src);h=0!==h.indexOf("blob:")?h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var ca=f.print||console.log.bind(console),m=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.quit&&(ba=f.quit);var r;f.wasmBinary&&(r=f.wasmBinary);"object"!=typeof WebAssembly&&t("no native wasm support detected");
var da,ea=!1,w,x,z,A,fa=[],ha=[],ia=[];function ja(){var a=f.preRun.shift();fa.unshift(a)}var B=0,ka=null,C=null;function t(a){f.onAbort?.(a);a="Aborted("+a+")";m(a);ea=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var la=a=>a.startsWith("data:application/octet-stream;base64,"),E;E="edid-decode.wasm";if(!la(E)){var ma=E;E=f.locateFile?f.locateFile(ma,h):h+ma}
function na(a){if(a==E&&r)return new Uint8Array(r);throw"both async and sync fetching of the wasm failed";}function oa(a){return r||"function"!=typeof fetch?Promise.resolve().then(()=>na(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>na(a))}function pa(a,b,c){return oa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);t(d)})}
function qa(a,b){var c=E;r||"function"!=typeof WebAssembly.instantiateStreaming||la(c)||"function"!=typeof fetch?pa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return pa(c,a,b)}))}var F,ra;function ta(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var ua=a=>{for(;0<a.length;)a.shift()(f)},va=f.noExitRuntime||!0;function wa(a){this.V=a-24;this.oa=function(b){A[this.V+4>>2]=b};this.na=function(b){A[this.V+8>>2]=b};this.N=function(b,c){this.ma();this.oa(b);this.na(c)};this.ma=function(){A[this.V+16>>2]=0}}
var xa=0,ya=0,za=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},G=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=za(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Aa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},
Ba=a=>{if("/"===a)return"/";a=G(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ca=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);t("initRandomDevice")},Da=a=>(Da=Ca())(a);
function H(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=za(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Ea="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,I=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ea)return Ea.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},
Fa=[],Ga=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ha=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var n=a.charCodeAt(++g);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&
63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e},Ia=[];function Ja(a,b){Ia[a]={input:[],D:[],M:b};Ka(a,La)}
var La={open(a){var b=Ia[a.node.W];if(!b)throw new J(43);a.F=b;a.seekable=!1},close(a){a.F.M.S(a.F)},S(a){a.F.M.S(a.F)},read(a,b,c,d){if(!a.F||!a.F.M.ea)throw new J(60);for(var e=0,g=0;g<d;g++){try{var k=a.F.M.ea(a.F)}catch(n){throw new J(29);}if(void 0===k&&0===e)throw new J(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.F||!a.F.M.Z)throw new J(60);try{for(var e=0;e<d;e++)a.F.M.Z(a.F,b[c+e])}catch(g){throw new J(29);}d&&(a.node.timestamp=
Date.now());return e}},Ma={ea(){a:{if(!Fa.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(Ga(a)+1);a=Ha(a,b,0,b.length);b.length=a;Fa=b}b=Fa.shift()}return b},Z(a,b){null===b||10===b?(ca(I(a.D,0)),a.D=[]):0!=b&&a.D.push(b)},S(a){a.D&&0<a.D.length&&(ca(I(a.D,0)),a.D=[])},Ha(){return{za:25856,Ba:5,ya:191,Aa:35387,xa:[3,28,
127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ia(){return 0},Ja(){return[24,80]}},Na={Z(a,b){null===b||10===b?(m(I(a.D,0)),a.D=[]):0!=b&&a.D.push(b)},S(a){a.D&&0<a.D.length&&(m(I(a.D,0)),a.D=[])}};function Oa(a,b){var c=a.A?a.A.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.A,a.A=new Uint8Array(b),0<a.C&&a.A.set(c.subarray(0,a.C),0))}
var K={G:null,I(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.G||(K.G={dir:{node:{J:K.v.J,H:K.v.H,P:K.v.P,T:K.v.T,ja:K.v.ja,la:K.v.la,ka:K.v.ka,ia:K.v.ia,X:K.v.X},stream:{L:K.B.L}},file:{node:{J:K.v.J,H:K.v.H},stream:{L:K.B.L,read:K.B.read,write:K.B.write,aa:K.B.aa,fa:K.B.fa,ha:K.B.ha}},link:{node:{J:K.v.J,H:K.v.H,R:K.v.R},stream:{}},ba:{node:{J:K.v.J,H:K.v.H},stream:Pa}});c=Qa(a,b,c,d);16384===(c.mode&61440)?(c.v=K.G.dir.node,
c.B=K.G.dir.stream,c.A={}):32768===(c.mode&61440)?(c.v=K.G.file.node,c.B=K.G.file.stream,c.C=0,c.A=null):40960===(c.mode&61440)?(c.v=K.G.link.node,c.B=K.G.link.stream):8192===(c.mode&61440)&&(c.v=K.G.ba.node,c.B=K.G.ba.stream);c.timestamp=Date.now();a&&(a.A[b]=c,a.timestamp=c.timestamp);return c},Ea(a){return a.A?a.A.subarray?a.A.subarray(0,a.C):new Uint8Array(a.A):new Uint8Array(0)},v:{J(a){var b={};b.Da=8192===(a.mode&61440)?a.id:1;b.Ga=a.id;b.mode=a.mode;b.La=1;b.uid=0;b.Fa=0;b.W=a.W;16384===(a.mode&
61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.C:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.va=new Date(a.timestamp);b.Ka=new Date(a.timestamp);b.Ca=new Date(a.timestamp);b.pa=4096;b.wa=Math.ceil(b.size/b.pa);return b},H(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.C!=b))if(0==b)a.A=null,a.C=0;else{var c=a.A;a.A=new Uint8Array(b);c&&a.A.set(c.subarray(0,Math.min(b,a.C)));a.C=b}},P(){throw Ra[44];},T(a,b,c,d){return K.createNode(a,
b,c,d)},ja(a,b,c){if(16384===(a.mode&61440)){try{var d=L(b,c)}catch(g){}if(d)for(var e in d.A)throw new J(55);}delete a.parent.A[a.name];a.parent.timestamp=Date.now();a.name=c;b.A[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},la(a,b){delete a.A[b];a.timestamp=Date.now()},ka(a,b){var c=L(a,b),d;for(d in c.A)throw new J(55);delete a.A[b];a.timestamp=Date.now()},ia(a){var b=[".",".."],c;for(c of Object.keys(a.A))b.push(c);return b},X(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},R(a){if(40960!==
(a.mode&61440))throw new J(28);return a.link}},B:{read(a,b,c,d,e){var g=a.node.A;if(e>=a.node.C)return 0;a=Math.min(a.node.C-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.A||a.A.subarray)){if(g)return a.A=b.subarray(c,c+d),a.C=d;if(0===a.C&&0===e)return a.A=b.slice(c,c+d),a.C=d;if(e+d<=a.C)return a.A.set(b.subarray(c,c+d),e),d}Oa(a,e+d);if(a.A.subarray&&b.subarray)a.A.set(b.subarray(c,
c+d),e);else for(g=0;g<d;g++)a.A[e+g]=b[c+g];a.C=Math.max(a.C,e+d);return d},L(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.C);if(0>b)throw new J(28);return b},aa(a,b,c){Oa(a.node,b+c);a.node.C=Math.max(a.node.C,b+c)},fa(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.A;if(e&2||a.buffer!==w.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;t();b=void 0;if(!b)throw new J(48);w.set(a,b)}else c=!1,b=
a.byteOffset;return{V:b,ua:c}},ha(a,b,c,d){K.B.write(a,b,0,d,c,!1);return 0}}},Sa=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ta=null,Ua={},M=[],Va=1,N=null,Wa=!0,J=null,Ra={};
function O(a,b={}){a=H(a);if(!a)return{path:"",node:null};b=Object.assign({da:!0,$:0},b);if(8<b.$)throw new J(32);a=a.split("/").filter(k=>!!k);for(var c=Ta,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=L(c,a[e]);d=G(d+"/"+a[e]);c.U&&(!g||g&&b.da)&&(c=c.U.root);if(!g||b.ca)for(g=0;40960===(c.mode&61440);)if(c=Xa(d),d=H(Aa(d),c),c=O(d,{$:b.$+1}).node,40<g++)throw new J(32);}return{path:d,node:c}}
function Ya(a){for(var b;;){if(a===a.parent)return a=a.I.ga,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Za(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%N.length}function L(a,b){var c;if(c=(c=P(a,"x"))?c:a.v.P?0:2)throw new J(c,a);for(c=N[Za(a.id,b)];c;c=c.ra){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.v.P(a,b)}function Qa(a,b,c,d){a=new $a(a,b,c,d);b=Za(a.parent.id,a.name);a.ra=N[b];return N[b]=a}
function ab(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function P(a,b){if(Wa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function bb(a,b){try{return L(a,b),20}catch(c){}return P(a,"wx")}function cb(){for(var a=0;4096>=a;a++)if(!M[a])return a;throw new J(33);}function Q(a){a=M[a];if(!a)throw new J(8);return a}
function db(a){var b=-1;R||(R=function(){this.N={}},R.prototype={},Object.defineProperties(R.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.N.flags},set(c){this.N.flags=c}},position:{get(){return this.N.position},set(c){this.N.position=c}}}));a=Object.assign(new R,a);-1==b&&(b=cb());a.K=b;return M[b]=a}var Pa={open(a){a.B=Ua[a.node.W].B;a.B.open?.(a)},L(){throw new J(70);}};function Ka(a,b){Ua[a]={B:b}}
function eb(a,b){var c="/"===b,d=!b;if(c&&Ta)throw new J(10);if(!c&&!d){var e=O(b,{da:!1});b=e.path;e=e.node;if(e.U)throw new J(10);if(16384!==(e.mode&61440))throw new J(54);}b={type:a,Ma:{},ga:b,qa:[]};a=a.I(b);a.I=b;b.root=a;c?Ta=a:e&&(e.U=b,e.I&&e.I.qa.push(b))}function fb(a,b,c){var d=O(a,{parent:!0}).node;a=Ba(a);if(!a||"."===a||".."===a)throw new J(28);var e=bb(d,a);if(e)throw new J(e);if(!d.v.T)throw new J(63);return d.v.T(d,a,b,c)}function V(a){return fb(a,16895,0)}
function W(a,b,c){"undefined"==typeof c&&(c=b,b=438);fb(a,b|8192,c)}function gb(a,b){if(!H(a))throw new J(44);var c=O(b,{parent:!0}).node;if(!c)throw new J(44);b=Ba(b);var d=bb(c,b);if(d)throw new J(d);if(!c.v.X)throw new J(63);c.v.X(c,b,a)}function Xa(a){a=O(a).node;if(!a)throw new J(44);if(!a.v.R)throw new J(28);return H(Ya(a.parent),a.v.R(a))}
function hb(a,b,c){if(""===a)throw new J(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=G(a);try{e=O(a,{ca:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new J(20);}else e=fb(a,c,0),d=!0;if(!e)throw new J(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new J(54);
if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==ab(b)||b&512)?31:P(e,ab(b)):44))throw new J(c);if(b&512&&!d){c=e;c="string"==typeof c?O(c,{ca:!0}).node:c;if(!c.v.H)throw new J(63);if(16384===(c.mode&61440))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(d=P(c,"w"))throw new J(d);c.v.H(c,{size:0,timestamp:Date.now()})}b&=-131713;e=db({node:e,path:Ya(e),flags:b,seekable:!0,position:0,B:e.B,ta:[],error:!1});e.B.open&&e.B.open(e);!f.logReadFiles||b&1||(ib||={},a in ib||
(ib[a]=1));return e}function jb(a,b,c){if(null===a.K)throw new J(8);if(!a.seekable||!a.B.L)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.B.L(a,b,c);a.ta=[]}function kb(){J||(J=function(a,b){this.name="ErrnoError";this.node=b;this.sa=function(c){this.O=c};this.sa(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(a=>{Ra[a]=new J(a);Ra[a].stack="<generic error, no stack>"}))}var lb;
function X(a,b,c){a=G("/dev/"+a);var d=Sa(!!b,!!c);mb||=64;var e=mb++<<8|0;Ka(e,{open(g){g.seekable=!1},close(){c?.buffer?.length&&c(10)},read(g,k,n,p){for(var l=0,q=0;q<p;q++){try{var u=b()}catch(v){throw new J(29);}if(void 0===u&&0===l)throw new J(6);if(null===u||void 0===u)break;l++;k[n+q]=u}l&&(g.node.timestamp=Date.now());return l},write(g,k,n,p){for(var l=0;l<p;l++)try{c(k[n+l])}catch(q){throw new J(29);}p&&(g.node.timestamp=Date.now());return l}});W(a,d,e)}
var mb,Y={},R,ib,nb=void 0,ob=[0,31,60,91,121,152,182,213,244,274,305,335],pb=[0,31,59,90,120,151,181,212,243,273,304,334],rb=a=>{var b=Ga(a)+1,c=qb(b);c&&Ha(a,x,c,b);return c},vb=(a,b,c,d)=>{var e={string:l=>{var q=0;if(null!==l&&void 0!==l&&0!==l){q=Ga(l)+1;var u=sb(q);Ha(l,x,u,q);q=u}return q},array:l=>{var q=sb(l.length);w.set(l,q);return q}};a=f["_"+a];var g=[],k=0;if(d)for(var n=0;n<d.length;n++){var p=e[c[n]];p?(0===k&&(k=tb()),g[n]=p(d[n])):g[n]=d[n]}c=a.apply(null,g);return c=function(l){0!==
k&&ub(k);return"string"===b?l?I(x,l):"":"boolean"===b?!!l:l}(c)};function $a(a,b,c,d){a||=this;this.parent=a;this.I=a.I;this.U=null;this.id=Va++;this.name=b;this.mode=c;this.v={};this.B={};this.W=d}Object.defineProperties($a.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});kb();N=Array(4096);eb(K,"/");V("/tmp");V("/home");V("/home/web_user");
(function(){V("/dev");Ka(259,{read:()=>0,write:(d,e,g,k)=>k});W("/dev/null",259);Ja(1280,Ma);Ja(1536,Na);W("/dev/tty",1280);W("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Da(a).byteLength);return a[--b]};X("random",c);X("urandom",c);V("/dev/shm");V("/dev/shm/tmp")})();(function(){V("/proc");var a=V("/proc/self");V("/proc/self/fd");eb({I(){var b=Qa(a,"fd",16895,73);b.v={P(c,d){var e=Q(+d);c={parent:null,I:{ga:"fake"},v:{R:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var wb={c:(a,b,c)=>{(new wa(a)).N(b,c);xa=a;ya++;throw xa;},h:function(a,b,c,d){nb=d;try{b=b?I(x,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var g=-100===a?"/":Q(a).path;if(0==e.length)throw new J(44);b=G(g+"/"+e)}if(d){var k=z[+nb>>2];nb+=4;var n=k}else n=0;return hb(b,c,n).K}catch(p){if("undefined"==typeof Y||"ErrnoError"!==p.name)throw p;return-p.O}},l:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));z[c>>2]=a.getSeconds();z[c+4>>2]=a.getMinutes();z[c+8>>2]=
a.getHours();z[c+12>>2]=a.getDate();z[c+16>>2]=a.getMonth();z[c+20>>2]=a.getFullYear()-1900;z[c+24>>2]=a.getDay();b=a.getFullYear();z[c+28>>2]=(0!==b%4||0===b%100&&0!==b%400?pb:ob)[a.getMonth()]+a.getDate()-1|0;z[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},e:(a,b,c)=>{function d(p){return(p=p.toTimeString().match(/\(([A-Za-z ]+)\)$/))?
p[1]:"GMT"}var e=(new Date).getFullYear(),g=new Date(e,0,1),k=new Date(e,6,1);e=g.getTimezoneOffset();var n=k.getTimezoneOffset();A[a>>2]=60*Math.max(e,n);z[b>>2]=Number(e!=n);a=d(g);b=d(k);a=rb(a);b=rb(b);n<e?(A[c>>2]=a,A[c+4>>2]=b):(A[c>>2]=b,A[c+4>>2]=a)},b:()=>{t("")},j:()=>Date.now(),i:(a,b,c)=>x.copyWithin(a,b,b+c),d:()=>{t("OOM")},m:a=>{va||(f.onExit?.(a),ea=!0);ba(a,new ta(a))},a:function(a){try{var b=Q(a);if(null===b.K)throw new J(8);b.Y&&(b.Y=null);try{b.B.close&&b.B.close(b)}catch(c){throw c;
}finally{M[b.K]=null}b.K=null;return 0}catch(c){if("undefined"==typeof Y||"ErrnoError"!==c.name)throw c;return c.O}},g:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var g,k=b=0;k<c;k++){var n=A[a>>2],p=A[a+4>>2];a+=8;var l=e,q=n,u=p,v=g,sa=w;if(0>u||0>v)throw new J(28);if(null===l.K)throw new J(8);if(1===(l.flags&2097155))throw new J(8);if(16384===(l.node.mode&61440))throw new J(31);if(!l.B.read)throw new J(28);var S="undefined"!=typeof v;if(!S)v=l.position;else if(!l.seekable)throw new J(70);var T=
l.B.read(l,sa,q,u,v);S||(l.position+=T);var y=T;if(0>y){var U=-1;break a}b+=y;if(y<p)break;"undefined"!==typeof g&&(g+=y)}U=b}A[d>>2]=U;return 0}catch(D){if("undefined"==typeof Y||"ErrnoError"!==D.name)throw D;return D.O}},k:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var g=Q(a);jb(g,b,d);ra=[g.position>>>0,(F=g.position,1<=+Math.abs(F)?0<F?+Math.floor(F/4294967296)>>>0:~~+Math.ceil((F-+(~~F>>>0))/4294967296)>>>0:0)];z[e>>2]=ra[0];z[e+4>>2]=ra[1];
g.Y&&0===b&&0===d&&(g.Y=null);return 0}catch(k){if("undefined"==typeof Y||"ErrnoError"!==k.name)throw k;return k.O}},f:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var g,k=b=0;k<c;k++){var n=A[a>>2],p=A[a+4>>2];a+=8;var l=e,q=n,u=p,v=g,sa=w;if(0>u||0>v)throw new J(28);if(null===l.K)throw new J(8);if(0===(l.flags&2097155))throw new J(8);if(16384===(l.node.mode&61440))throw new J(31);if(!l.B.write)throw new J(28);l.seekable&&l.flags&1024&&jb(l,0,2);var S="undefined"!=typeof v;if(!S)v=l.position;else if(!l.seekable)throw new J(70);
var T=l.B.write(l,sa,q,u,v,void 0);S||(l.position+=T);var y=T;if(0>y){var U=-1;break a}b+=y;"undefined"!==typeof g&&(g+=y)}U=b}A[d>>2]=U;return 0}catch(D){if("undefined"==typeof Y||"ErrnoError"!==D.name)throw D;return D.O}}},Z=function(){function a(c){Z=c.exports;da=Z.n;c=da.buffer;f.HEAP8=w=new Int8Array(c);f.HEAP16=new Int16Array(c);f.HEAPU8=x=new Uint8Array(c);f.HEAPU16=new Uint16Array(c);f.HEAP32=z=new Int32Array(c);f.HEAPU32=A=new Uint32Array(c);f.HEAPF32=new Float32Array(c);f.HEAPF64=new Float64Array(c);
ha.unshift(Z.o);B--;f.monitorRunDependencies?.(B);0==B&&(null!==ka&&(clearInterval(ka),ka=null),C&&(c=C,C=null,c()));return Z}var b={a:wb};B++;f.monitorRunDependencies?.(B);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}qa(b,function(c){a(c.instance)});return{}}();f._parse_edid=a=>(f._parse_edid=Z.p)(a);var qb=a=>(qb=Z.r)(a),tb=()=>(tb=Z.s)(),ub=a=>(ub=Z.t)(a),sb=a=>(sb=Z.u)(a);f.ccall=vb;
f.cwrap=(a,b,c,d)=>{var e=!c||c.every(g=>"number"===g||"boolean"===g);return"string"!==b&&e&&!d?f["_"+a]:function(){return vb(a,b,c,arguments,d)}};var xb;C=function yb(){xb||zb();xb||(C=yb)};
function zb(){function a(){if(!xb&&(xb=!0,f.calledRun=!0,!ea)){f.noFSInit||lb||(lb=!0,kb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?X("stdin",f.stdin):gb("/dev/tty","/dev/stdin"),f.stdout?X("stdout",null,f.stdout):gb("/dev/tty","/dev/stdout"),f.stderr?X("stderr",null,f.stderr):gb("/dev/tty1","/dev/stderr"),hb("/dev/stdin",0),hb("/dev/stdout",1),hb("/dev/stderr",1));Wa=!1;ua(ha);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=
[f.postRun]);f.postRun.length;){var b=f.postRun.shift();ia.unshift(b)}ua(ia)}}if(!(0<B)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ja();ua(fa);0<B||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();zb();
